### ISSUE TITLE
Would you consider adding screenshots to addons.thunderbird.net?

### ISSUE THREAD

**Issue by pbarney** [thestonehead/ThunderbirdAttachmentExtractor#1]
Many people have refused to upgrade TB past 68.12.1 due to the WebExtension change that broke many well-loved extensions, AttachmentExtractor among them. In looking for a replacement, I came upon your offering, but there are no screen shots to help people decide if it's for them.

Would you consider adding screenshots to the addons page?

Thanks

**Comment by thestonehead** [comment]
I have added screenshots. Thanks.
