### ISSUE TITLE
It still does not work in TB v115.1

### ISSUE THREAD

**Issue by cjchome** [thestonehead/ThunderbirdAttachmentExtractor#17]
It still does not work in TB v115.1
![1](https://github.com/thestonehead/ThunderbirdAttachmentExtractor/assets/30073216/fde01418-ff04-4c31-8c3a-85cf8d4ef5aa)
![2](https://github.com/thestonehead/ThunderbirdAttachmentExtractor/assets/30073216/76683590-77c8-44be-81bf-96d55c4553b1)

**Comment by thestonehead** [comment]
Can you try the new 1.6 version? Is it still happening?

**Comment by cjchome** [comment]
V1.6 is working normally now, thank you.
