### ISSUE TITLE
TB 102.14.0 (64-bit) Attachment Extractor V1.6

### ISSUE THREAD

**Issue by Shyanha** [thestonehead/ThunderbirdAttachmentExtractor#19]
Attachment Extractor seems to be doing nothing when I select "Extract Attachments."  The screen doesn't blink, there are no error messages, and it Looks like nothing happens.  

I removed Attachment Extractor, restarted Thunderbird, re-downloaded Attachment Extractor, restarted Thunderbird, then tried to extract but nothing happened.

I'm unsure what else I could do to test.  I don't have any options to update TB, but I saw another user is on version 115 and got the add-on to work.  I'm reluctant to do that just yet as I don't have extra time to work through figuring out new features, or potential issues.  When my assistant is back in the office I can, but for now I'm trying to keep my head above water.  Until then, if y'all have any ideas I'm up to trying this or that.  Thank you!

**Comment by thestonehead** [comment]
Will look into it. Thanks

**Comment by thestonehead** [comment]
Yup. I broke the fix.
Version 1.7 should be up today with a solution. 
Please try with it.

**Comment by Shyanha** [comment]
I was able to update it today and we're back in business.  Thank you!
