### ISSUE TITLE
Detaching or Deleting: Please specify in Readme / Documentation

### ISSUE THREAD

**Issue by Johann-Tree** [thestonehead/ThunderbirdAttachmentExtractor#2]
Is the AddOn deleting the saved attachments or is it detaching them, so you can still access the files by clicking the links in the attachment pane? 
Please specify in the Readme and on addons.thunderbird.net .

**Comment by thestonehead** [comment]
After it saves attachments, it will ask you if you want to delete them from the e-mails. So it will do one or the other, depending on user's choice.

I'll add it to the readme. Thanks.

**Comment by Johann-Tree** [comment]
Thanks, but it's still not clear if the file-URL to the saved attachment is then saved in the e-mail (aka detaching) or not (this case is called deleting in Thunderbird).
Saving and deleting but not detaching would be not useful for me. I still want to be able to access the attachments directly from the originating e-mail.
