### ISSUE TITLE
TB 128 ?

### ISSUE THREAD

**Issue by goofie45** [thestonehead/ThunderbirdAttachmentExtractor#25]
Superb addons, but is a TB 128 version planned?
good luck

**Comment by goofie45** [comment]
Thank you.
The attachments are registered correctly.
The cancel button in the first popup is not operational (same action as the ok button, redirection to the folder selection).
No access to the module's configuration menu to change the names of files to be saved.
Have a nice day!

**Comment by Martin511** [comment]
Thank you @jobisoft !!
Maybe @thestonehead is no longer active?
Do we have alternatives to get ThunderbirdAttachmentExtractor running under Thunderbird again? I found this Add-On very useful.

**Comment by jobisoft** [comment]
@goofie45 : I fixed the cancel button not working, but I do not know what configuration menu you are referring to. The version for 115 does not have an option page. Could you post some instructions where I can find that menu in 115? Thanks!

@Martin511 : There is https://addons.thunderbird.net/addon/extract-em/ but I am not sure it is the exact same use case. I hope @thestonehead is just on his well deserved summer vacation and will respond in a few weeks.

**Comment by Martin511** [comment]
@jobisoft Thanks for the hint, but Extract 'em doesn't seem tohave an option to  _delete_ the (extracted) attachments. And this is essential in my case.

**Comment by jobisoft** [comment]
Ping the author, we definitely have an api to delete (but not to detach) an attachment. He is very active.

**Comment by Martin511** [comment]
I´ll wait for @thestonehead first as the summer holidays are nearly ending. And it´s not urgent, just nice to have it back.

**Comment by thestonehead** [comment]
@Martin511 I'll look into it.

**Comment by PaoloPC** [comment]
> @Martin511 I'll look into it.

Hi @thestonehead, any news on the new release?

Thank you very much!
